---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: jrjohnsongoog/stackdriver-tools-ci
inputs:
  - name: stackdriver-tools
  - name: stackdriver-tools-artifacts
  - name: stackdriver-tools-artifacts-sha1
  - name: version-semver
outputs:
  - name: candidate

run:
  path: stackdriver-tools/ci/tasks/deploy-candidate.sh
params:
  # BOSH and CF settings
  bosh_director_address: replace-me
  bosh_user:             replace-me
  bosh_password:         replace-me
  cf_deployment_name:    replace-me

  # CF settings
  vip_ip:          replace-me
  common_password: replace-me

  # Google network settings
  google_region:      replace-me
  google_zone:        replace-me
  network:            replace-me
  public_subnetwork:  replace-me
  private_subnetwork: replace-me

  # Google service account settings
  cf_project_id:           replace-me
  cf_service_account_json: replace-me


  ## SSH
  ssh_bastion_address: replace-me
  ssh_user:         replace-me
  ssh_key:          replace-me
