---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lambr/gcp-tools
    tag: v3
inputs:
  - name: gcp-tools-release
run:
  path: gcp-tools-release/ci/tasks/public-semver.sh
params:
  # Google service account settings
  project_id:               replace me
  service_account_key_json: replace me
  bucket_name:              replace me
  semver_key:               replace me
