---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lambr/gcp-tools
    tag: v3
inputs:
  - name: stackdriver-tools
run:
  path: stackdriver-tools/ci/tasks/unit-tests.sh
