source 'https://rubygems.org'

gem 'fluent-plugin-google-cloud', '~> 0.6.15'
gem 'fluent-plugin-detect-exceptions', '0.0.3'
gem 'fluentd', '~> 0.12'
gem 'google-api-client', '~> 0.17.0'
gem 'googleauth', '~> 0.6.0'
