---
<%
director_uuid = ""
firehose_endpoint = ""
firehose_username = ""
firehose_password = ""
service_account = ""
zone = ""
network_name = ""
subnetwork_name = ""
%>
name: stackdriver-nozzle-wtf
director_uuid: <%= director_uuid %>

releases:
- name: bosh-gcp-tools
  version: latest

jobs:
- name: stackdriver-nozzle
  instances: 2
  networks:
  - name: private
  resource_pool: nozzle_pool
  templates:
  - name: stackdriver-nozzle
    release: bosh-gcp-tools
  - name: google-fluentd
    release: bosh-gcp-tools
  - name: stackdriver-agent
    release: bosh-gcp-tools
  properties:
    firehose:
      endpoint: <%= firehose_endpoint %>
      username: <%= firehose_username %>
      password: <%= firehose_password %>
      skip_ssl: true

compilation:
  workers: 3
  network: private
  reuse_compilation_vms: true
  cloud_properties:
    zone: <%= zone %>
    machine_type: n1-standard-8
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true

resource_pools:
- name: nozzle_pool
  network: private
  stemcell:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    zone: <%= zone %>
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    service_account: <%= service_account %>

networks:
- name: private
  type: dynamic
  cloud_properties:
    zone: <%= zone %>
    network_name: <%= network_name %>
    subnetwork_name: <%= subnetwork_name %>
    ephemeral_external_ip: false
    tags:
    - internal
    - no-ip

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

