---
<%
director_uuid = "CHANGE-ME"
vip_ip = "CHANGE-ME"
root_domain = "#{vip_ip}.xip.io"
common_password = "c1oudc0w"
deployment_name = "gcp-tools"
%>
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
  - name: gcp-tools
    version: 1

compilation:
  workers: 3
  network: private
  reuse_compilation_vms: true
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: private
    type: dynamic
    cloud_properties:
      network_name: cf
      ephemeral_external_ip: true
      tags:
        - cf-internal

resource_pools:
  - name: common
    network: private
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 20
      root_disk_type: pd-standard
      service_scopes:
        - logging.write

jobs:
  - name: google-fluentd
    templates:
      - name: google-fluentd
        release: gcp-tools
      - name: stackdriver-agent
        release: gcp-tools
    instances: 1
    resource_pool: common
    networks:
      - name: private
        default: [dns, gateway]
